### ISSUE TITLE
Web cam support

### ISSUE THREAD

**Issue by milengg** [tshino/compare#41]
Excellent App!
How I can add web-camera support to this application? I like instead of uploading image, to take a shot from web-cam and crop some part from it.

**Comment by tshino** [comment]
Thank you for great idea!
Actually, on mobile browsers, it is already able to use camera app to feed a picture to Compare.
So it makes sense to support cameras also on PC browsers.
I will study related APIs.
And now, I'm very happy because this is my first time to receive an issue from someone.
Thank you.

**Comment by tshino** [comment]
Hi @milengg ,
I have just implemented camera support.
Basically it works for me on Chrome and Firefox on Windows.
Since it seems small problems like error handling still remain, I keep this issue open for a while.
Please feel free to make any comments or another requests.

**Comment by tshino** [comment]
Almost done.
Thank you.

**Comment by tshino** [comment]
My understanding is that you want to customize this app so that you can use a new button to load images from an URL or other way.
Well, my answer is that addFiles(files) and addCapturedImage(canvas) in compare.js are the only safe way to add new images to this app in this moment.
If you can adapt your images to kind of FileList or Canvas, then you can use one of above functions.
I could imagine to implement a new function named addImageFromURL(url) which load a file from URL using XMLHttpRequest and add it to the app, but unfortunatly such a function has not been implemented yet.
